### PR TITLE
compat for NamedDims

### PR DESCRIPTION
**Pull request by mzgubic**

### CODE REVIEW

**Comment by mzgubic** [comment]
@mcabbott would you be able to run the CI and merge this please?

**Comment by mzgubic** [comment]
bump

**Comment by mzgubic** [comment]
Thanks for running CI  - nightly fails but it doesn't seem to be related...could we go ahead and merge this?

**Comment by mcabbott** [comment]
Sure, sorry about the delay, let's do it.

Curious how you use this, is it just a dep of something or do you need its NamedDims functionality? I left it at `0.0.x` because (if I remember right) I wasn't happy with the mechanism of this. But it's probably overdue for an overhaul, esp in as `Base.stack` is at last merged. Is it worth keeping name handling?

**Comment by mzgubic** [comment]
Thanks! We use AxisKeys internally and LazyStack is a dependency. We needed one particular bugfix that landed after 1.0 of NamedDims. So not using LazyStack directly :)

**Comment by mcabbott** [comment]
Oh right, I forgot that. Thanks!

**Pull request merged**
